minecraft_version=26.1
loader_version=0.19.5
loom_version=1.17.20
loom_plugin=net.fabricmc.fabric-loom
fabric_version=0.155.2+26.1.2
modmenu_version=18.0.0
remap=false
java_version=25
mixin_level=JAVA_25
port=port26
loader_req=0.19.0
mc_range==26.1
api_id=fabric-api
