minecraft_version=26.2
loader_version=0.19.5
loom_version=1.17.20
loom_plugin=net.fabricmc.fabric-loom
fabric_version=0.159.0+26.2
modmenu_version=20.0.1
remap=false
java_version=25
mixin_level=JAVA_25
port=port262
loader_req=0.19.0
mc_range==26.2
api_id=fabric-api
